In [1]:
import os
import glob
import pandas as pd
import numpy as np

In [2]:
datafolder = 'E:\Congcong\Documents\data\comparison\data-summary'
session_file = os.path.join(datafolder, 'sessions.json')
su_file = os.path.join(datafolder, 'single_units.json')
ne_file =  os.path.join(datafolder, 'split_cNE.json')

sessions = pd.read_json(session_file)
su = pd.read_json(su_file)
ne = pd.read_json(ne_file)

In [3]:
sessions.head()

,exp,site,depth,probe,file_path,dmr_first,n_neuron,min_freq,max_freq,freq_span_oct
0,191126211411,5,5214,H31x64,E:\Congcong\Documents\data\comparison\data-pkl...,True,12,1521.578789,40000.000000,4.716359
1,200127153707,2,5004,H31x64,E:\Congcong\Documents\data\comparison\data-pkl...,True,9,8077.577010,40000.000000,2.308005
2,200709232021,1,1300,H22x32,E:\Congcong\Documents\data\comparison\data-pkl...,False,30,8077.577010,34805.224244,2.107309
3,200709232021,1,5300,H31x64,E:\Congcong\Documents\data\comparison\data-pkl...,False,16,1235.011816,24581.339688,4.314967
4,200710002633,2,1000,H22x32,E:\Congcong\Documents\data\comparison\data-pkl...,True,17,8077.577010,26351.984471,1.705917

In [6]:
sessions[sessions.n_neuron < 10]

,exp,site,depth,probe,file_path,dmr_first,n_neuron,min_freq,max_freq,freq_span_oct
1,200127153707,2,5004,H31x64,E:\Congcong\Documents\data\comparison\data-pkl...,True,9,8077.577010,40000.000000,2.308005
6,200729211319,1,6200,H31x64,E:\Congcong\Documents\data\comparison\data-pkl...,True,9,8659.421603,40000.000000,2.207657
9,200814004349,6,6008,H31x64,E:\Congcong\Documents\data\comparison\data-pkl...,True,7,5321.504598,40000.000000,2.910094
27,201210162834,1,5155,H31x64,E:\Congcong\Documents\data\comparison\data-pkl...,False,8,11437.207359,37312.316596,1.705917
48,210715201351,3,5000,H31x64,E:\Congcong\Documents\data\comparison\data-pkl...,True,9,1235.011816,40000.000000,5.017403

In [4]:
su.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 948 entries, 0 to 947
Data columns (total 29 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         948 non-null    int64
 1   unit          948 non-null    int64
 2   chan          948 non-null    int64
 3   isolation     948 non-null    float64
 4   isi_vio       948 non-null    float64
 5   strf          948 non-null    object
 6   strf_taxis    948 non-null    object
 7   strf_faxis    948 non-null    object
 8   strf_ri       948 non-null    object
 9   strf_ri_null  948 non-null    object
 10  strf_ri_z     948 non-null    float64
 11  strf_ri_p     948 non-null    float64
 12  crh           948 non-null    object
 13  tmfaxis       948 non-null    object
 14  smfaxis       948 non-null    object
 15  crh_ri        948 non-null    object
 16  crh_ri_null   948 non-null    object
 17  crh_ri_z      948 non-null    float64
 18  crh_ri_p      948 non-null    float64
 19  bf            948 non-null    float64
 20  latency       948 non-null    int64
 21  position      948 non-null    object
 22  strf_sig      948 non-null    bool
 23  btmf          948 non-null    float64
 24  bsmf          948 non-null    float64
 25  crh_sig       948 non-null    bool
 26  exp           948 non-null    int64
 27  depth         948 non-null    int64
 28  probe         948 non-null    object
dtypes: bool(2), float64(9), int64(6), object(12)
memory usage: 209.2+ KB

In [5]:
ne.head()

,exp,probe,region,stim,dmr_first,idx1,idx2,pattern1,pattern2,corr,corr_thresh,corr_sig,n_neuron,freq_span_oct,member1,member2,member_all,member_share,freq_span_oct_all,freq_span_oct_share
0,210715201351,H31x64,MGB,dmr,True,1,0,"[0.0897109132, 0.4638610554, -0.0627908716, 0....","[0.3677574738, 0.329001074, 0.2689638788, 0.35...",0.614550,0.801884,False,9,5.017403,"[1, 6, 7]","[0, 3, 5, 6]","[0, 1, 3, 5, 6, 7]",[6],4.013923,NaN
1,210715201351,H31x64,MGB,spon,True,0,1,"[0.3835528634, 0.18605720850000002, 0.23607617...","[-0.02636698, -0.1892202342, 0.5495066334, 0.3...",0.206984,0.803760,False,9,5.017403,"[0, 3, 4, 5, 8]","[2, 4]","[0, 2, 3, 4, 5, 8]",[4],5.017403,NaN
2,210715201351,H31x64,MGB,cross,True,0,0,"[0.3677574738, 0.329001074, 0.2689638788, 0.35...","[0.3835528634, 0.18605720850000002, 0.23607617...",0.279742,0.807811,False,9,5.017403,"[0, 3, 5, 6]","[0, 3, 4, 5, 8]","[0, 3, 4, 5, 6, 8]","[0, 3, 5]",5.017403,2.910094
3,210223165503,H31x64,MGB,dmr,False,0,2,"[0.3796602112, 0.4855612644, 0.439590939, 0.32...","[0.3282171698, 0.25629792230000004, 0.53166170...",0.902069,0.642110,True,15,5.318447,"[0, 1, 2, 3, 4]","[0, 2, 3, 4]","[0, 1, 2, 3, 4]","[0, 2, 3, 4]",1.906613,1.103829
4,210223165503,H31x64,MGB,dmr,False,2,0,"[-0.26819974820000003, -0.291174998, 0.1085772...","[-0.31949930330000004, -0.2658897806, 0.056801...",0.943359,0.642110,True,15,5.318447,"[6, 7, 9]","[6, 7, 9]","[6, 7, 9]","[6, 7, 9]",0.301044,0.301044

### get frequency span of recordings and cNEs

In [14]:
su_sig = su[su.strf_sig]
freq_span = su_sig.groupby(by=['exp', 'probe'])['bf'].agg(min_freq = 'min', max_freq = 'max')
freq_span['freq_span_oct'] = np.log2(freq_span.max_freq / freq_span.min_freq)
sessions = sessions.join(freq_span, on=['exp', 'probe'])
sessions.to_json(session_file)

In [21]:
freq_span.head()

                        min_freq      max_freq  freq_span_oct
exp          probe
191126211411 H31x64  1521.578789  40000.000000       4.716359
200127153707 H31x64  8077.577010  40000.000000       2.308005
200709232021 H22x32  8077.577010  34805.224244       2.107309
             H31x64  1235.011816  24581.339688       4.314967
200710002633 H22x32  8077.577010  26351.984471       1.705917

In [25]:
ne['member1'] = ne['pattern1'].apply(lambda x: np.where(x > 1/np.sqrt(len(x)))[0])
ne['member2'] = ne['pattern2'].apply(lambda x: np.where(x > 1/np.sqrt(len(x)))[0])
ne['member_all'] = ne[['member1', 'member2']].apply(np.concatenate, axis=1).apply(np.unique)
ne['member_share'] = ne[['member1', 'member2']].apply(lambda x: np.intersect1d(*x), axis=1)
freq_span_all = []
freq_span_share = []
for i in range(len(ne)):
    pair = ne.iloc[i]
    exp = pair.exp
    probe = pair.probe
    members = su_sig[(su_sig.exp == exp) & (su_sig.probe == probe)]
    # get frequency span of combined members
    members_all = members[members['index'].apply(lambda x: x in pair.member_all)]
    if len(members_all) > 1:
        freq_span_all.append(np.log2(members_all.bf.max() / members_all.bf.min()))
    else:
        freq_span_all.append(np.nan)
    # get frequency span of shared members
    members_share = members[members['index'].apply(lambda x: x in pair.member_share)]
    if len(members_share) > 1:
        freq_span_share.append(np.log2(members_share.bf.max() / members_share.bf.min()))
    else:
        freq_span_share.append(np.nan)
ne['freq_span_oct_all'] = freq_span_all
ne['freq_span_oct_share'] = freq_span_share
ne.to_json(ne_file)

In [26]:
ne.head()

,exp,probe,region,stim,dmr_first,idx1,idx2,pattern1,pattern2,corr,corr_thresh,corr_sig,n_neuron,member1,member2,member_all,member_share,freq_span_oct_all,freq_span_oct_share,freq_span_oct
0,210715201351,H31x64,MGB,dmr,True,1,0,"[0.0897109132, 0.4638610554, -0.0627908716, 0....","[0.3677574738, 0.329001074, 0.2689638788, 0.35...",0.614550,0.801884,False,9,"[1, 6, 7]","[0, 3, 5, 6]","[0, 1, 3, 5, 6, 7]",[6],4.013923,NaN,5.017403
1,210715201351,H31x64,MGB,spon,True,0,1,"[0.3835528634, 0.18605720850000002, 0.23607617...","[-0.02636698, -0.1892202342, 0.5495066334, 0.3...",0.206984,0.803760,False,9,"[0, 3, 4, 5, 8]","[2, 4]","[0, 2, 3, 4, 5, 8]",[4],5.017403,NaN,5.017403
2,210715201351,H31x64,MGB,cross,True,0,0,"[0.3677574738, 0.329001074, 0.2689638788, 0.35...","[0.3835528634, 0.18605720850000002, 0.23607617...",0.279742,0.807811,False,9,"[0, 3, 5, 6]","[0, 3, 4, 5, 8]","[0, 3, 4, 5, 6, 8]","[0, 3, 5]",5.017403,2.910094,5.017403
3,210223165503,H31x64,MGB,dmr,False,0,2,"[0.3796602112, 0.4855612644, 0.439590939, 0.32...","[0.3282171698, 0.25629792230000004, 0.53166170...",0.902069,0.642110,True,15,"[0, 1, 2, 3, 4]","[0, 2, 3, 4]","[0, 1, 2, 3, 4]","[0, 2, 3, 4]",1.906613,1.103829,5.318447
4,210223165503,H31x64,MGB,dmr,False,2,0,"[-0.26819974820000003, -0.291174998, 0.1085772...","[-0.31949930330000004, -0.2658897806, 0.056801...",0.943359,0.642110,True,15,"[6, 7, 9]","[6, 7, 9]","[6, 7, 9]","[6, 7, 9]",0.301044,0.301044,5.318447